/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as GatesRouteImport } from './routes/gates'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as MusterRouteImport } from './routes/muster'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SafetyAiRouteImport } from './routes/safety-ai'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesRoute = GatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const MusterRoute = MusterRouteImport.update({
  id: '/muster',
  path: '/muster',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyAiRoute = SafetyAiRouteImport.update({
  id: '/safety-ai',
  path: '/safety-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/gates': typeof GatesRoute
  '/hardware': typeof HardwareRoute
  '/knowledge': typeof KnowledgeRoute
  '/muster': typeof MusterRoute
  '/reports': typeof ReportsRoute
  '/safety-ai': typeof SafetyAiRoute
  '/work-orders': typeof WorkOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/gates': typeof GatesRoute
  '/hardware': typeof HardwareRoute
  '/knowledge': typeof KnowledgeRoute
  '/muster': typeof MusterRoute
  '/reports': typeof ReportsRoute
  '/safety-ai': typeof SafetyAiRoute
  '/work-orders': typeof WorkOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/gates': typeof GatesRoute
  '/hardware': typeof HardwareRoute
  '/knowledge': typeof KnowledgeRoute
  '/muster': typeof MusterRoute
  '/reports': typeof ReportsRoute
  '/safety-ai': typeof SafetyAiRoute
  '/work-orders': typeof WorkOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/digital-twin'
    | '/gates'
    | '/hardware'
    | '/knowledge'
    | '/muster'
    | '/reports'
    | '/safety-ai'
    | '/work-orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/digital-twin'
    | '/gates'
    | '/hardware'
    | '/knowledge'
    | '/muster'
    | '/reports'
    | '/safety-ai'
    | '/work-orders'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/digital-twin'
    | '/gates'
    | '/hardware'
    | '/knowledge'
    | '/muster'
    | '/reports'
    | '/safety-ai'
    | '/work-orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  GatesRoute: typeof GatesRoute
  HardwareRoute: typeof HardwareRoute
  KnowledgeRoute: typeof KnowledgeRoute
  MusterRoute: typeof MusterRoute
  ReportsRoute: typeof ReportsRoute
  SafetyAiRoute: typeof SafetyAiRoute
  WorkOrdersRoute: typeof WorkOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates': {
      id: '/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof GatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muster': {
      id: '/muster'
      path: '/muster'
      fullPath: '/muster'
      preLoaderRoute: typeof MusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-ai': {
      id: '/safety-ai'
      path: '/safety-ai'
      fullPath: '/safety-ai'
      preLoaderRoute: typeof SafetyAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  GatesRoute: GatesRoute,
  HardwareRoute: HardwareRoute,
  KnowledgeRoute: KnowledgeRoute,
  MusterRoute: MusterRoute,
  ReportsRoute: ReportsRoute,
  SafetyAiRoute: SafetyAiRoute,
  WorkOrdersRoute: WorkOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
